### ISSUE TITLE
Compilation Instructions and Dependencies. 

### ISSUE THREAD

**Issue by oshaboy** [increpare/magiewerkbank#1]
I am trying to compile it but nowhere does it say what dependencies does it require and how to compile it.

**Comment by increpare** [comment]
Thanks for taking the time to comment - a lot of my repos are for personal use chiefly - documenting them for others would be a lot of work all in all without much benefit to me (I try to keep some other bigger projects documented, like the pinned ones on my github home page - https://github.com/increpare (except for orthona, they're documented) ).  

In short: It's a haxe project - if you know haxegon it should be ok enough to compile, the question of dependencies doesn't come up. If not then http://haxegon.com has some resources.   

Best,

S
